# Generated by Django 5.0.6 on 2024-05-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Gender', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('Address', models.TextField()),
                ('BirthDate', models.DateField()),
                ('bloodGroup', models.CharField(max_length=5)),
            ],
        ),
    ]
